apiVersion: v1
kind: Namespace
metadata:
  name: spb
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: spb
  labels:
    app: demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: demo #名称
  namespace: spb
  labels:
    app: demo #标注 
spec:
  replicas: 1 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers: #docker容器的配置
      - name: demo
        image: demo:v4 # pull镜像的地址 ip:prot/dir/images:tag
        imagePullPolicy: IfNotPresent #pull镜像时机，
        ports:
        - containerPort: 8080 #容器对外开放端口
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: demo-kong-ingress
  namespace: spb
  annotations:
    kubernetes.io/ingress.class: kong
route:
  strip_path: true
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spb-ingress
  namespace: spb
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: demo-kong-ingress
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: demo
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spb-ingress2
  namespace: spb
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /demo/getAA
        backend:
          serviceName: demo
          servicePort: 80
